### ISSUE TITLE
Bug in entity repository and track relationship.

### ISSUE THREAD

**Issue by AbnerLin** [rockers7414/xmusic#21]
When I select the data from entity "Track" using SqlAlchemy, and "Repository" should load into Track automatically, but it's not. Maybe there is the problem of relationship settings.

**Comment by rockers7414** [comment]
@cclien0725 Please help to enhance this request. Thanks.

**Comment by cclien0725** [comment]
@AbnerLin Please help to test and review the pull request #22. Thanks.

**Comment by rockers7414** [comment]
@cclien0725 This issue isn't closed while merged your pull request. Could you guy study how to use this great function?
https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by AbnerLin** [comment]
@cclien0725 I tested the code and it work fine. Thanks ^^

**Comment by cclien0725** [comment]
@rockers7414 Sorry, I think referenced the issue ID can be closed when merged the pull request. So, do I close the issue by myself or @AbnerLin ?

**Comment by rockers7414** [comment]
@cclien0725 Sure.
