### ISSUE TITLE
Bug in socket client.

### ISSUE THREAD

**Issue by AbnerLin** [rockers7414/xmusic#23]
@rockers7414  I set the socket client buffer to 2048, but only get the length 1460 of response's data. Besides, Isn't it socket stream? why I still need to set the client receive buffer?
`response = str(sock.recv(1024), "utf-8")`

[client_console.txt](https://github.com/rockers7414/xmusic/files/830199/client_console.txt)
[xmusic-daemon.txt](https://github.com/rockers7414/xmusic/files/830200/xmusic-daemon.txt)

**Comment by rockers7414** [comment]
I'm not sure what's the detailed situation that you encountered, but I think the message header is needed right now. It'll let the receiver knows how many data need to read. ;)
